#!/bin/bash
mkdir cert
cd cert
openssl genrsa -out quiz-djfr-2015-key.pem 2048
openssl req -new -sha256 -key quiz-djfr-2015-key.pem -out quiz-djfr-2015-csr.pem
openssl x509 -req -in quiz-djfr-2015-csr.pem -signkey quiz-djfr-2015-key.pem -out quiz-djfr-2015-cert.pem
